apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamwizard-backend-command
spec:
  replicas: 5
  selector:
    matchLabels:
      app: streamwizard-backend-command
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled  # This annotation enables automatic injection
      labels:
        app: streamwizard-backend-command
    spec:
      containers:
        - name: streamwizard-backend-command
          image: ghcr.io/streamerbuddybot/commands:d94e979f9aff80b639098b3821a1481a3f7e01a6
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: streamwizard-backend
          volumeMounts:
            - name: grpc-dns
              mountPath: /usr/src/app/config.json
              subPath: config.json
              readOnly: true
      volumes:
        - name: grpc-dns
          configMap:
            name: grpc-dns
